direction: down

# Macro definitions
classes: {
  group: {
    direction: right
    style.stroke: transparent
    label: ""
  }
  node_container: {
    grid-columns: 3
    style.stroke: "#000000"
    style.fill: "#C1FFC1"
    label: ""
  }
  input_box: {
    style.fill: "#F0F0F0"
  }
  op_box: {
    style.fill: "#C1FFC1"
  }
  output_box: {
    style.fill: "#F0F0F0"
  }
  animated_edge: {
    style.animated: true
  }
}

# Group 1
group1: {
  class: group

  node1: {
    class: node_container

    input: |md
      input<br/>(2, 10)
    |
    input.class: input_box

    op: |md
      Linear<br/>depth: 2
    |
    op.class: op_box

    output: |md
      output<br/>(2, 20)
    |
    output.class: output_box
  }

  node2: {
    class: node_container

    input: |md
      input<br/>(2, 20)
    |
    input.class: input_box

    op: |md
      BatchNorm1d
      depth: 2
    |
    op.class: op_box

    output: |md
      output<br/>(2, 20)
    |
    output.class: output_box
  }

  node3: {
    class: node_container

    input: |md
      input<br/>(2, 20)
    |
    input.class: input_box

    op: |md
      ReLU<br/>depth: 2
    |
    op.class: op_box

    output: |md
      output<br/>(2, 20)
    |
    output.class: output_box
  }

  node1 -> node2 -> node3: {class: animated_edge}
}

# Group 2
group2: {
  class: group

  node1: {
    class: node_container

    input: |md
      input<br/>(2, 20)
    |
    input.class: input_box

    op: |md
      Linear<br/>depth: 2
    |
    op.class: op_box

    output: |md
      output<br/>(2, 15)
    |
    output.class: output_box
  }

  node2: {
    class: node_container

    input: |md
      input<br/>(2, 15)
    |
    input.class: input_box

    op: |md
      BatchNorm1d<br/>depth: 2
    |
    op.class: op_box

    output: |md
      output<br/>(2, 15)
    |
    output.class: output_box
  }

  node3: {
    class: node_container

    input: |md
      input<br/>(2, 15)
    |
    input.class: input_box

    op: |md
      ReLU<br/>depth: 2
    |
    op.class: op_box

    output: |md
      output<br/>(2, 15)
    |
    output.class: output_box
  }

  node1 -> node2 -> node3: {class: animated_edge}
}

# Group 3
group3: {
  class: group

  node1: {
    class: node_container

    input: |md
      input<br/>(2, 15)
    |
    input.class: input_box

    op: |md
      Linear<br/>depth: 2
    |
    op.class: op_box

    output: |md
      output<br/>(2, 5)
    |
    output.class: output_box
  }

  node2: {
    class: node_container

    input: |md
      input<br/>(2, 5)
    |
    input.class: input_box

    op: |md
      BatchNorm1d<br/>depth: 2
    |
    op.class: op_box

    output: |md
      output<br/>(2, 5)
    |
    output.class: output_box
  }

  node3: {
    class: node_container

    input: |md
      input<br/>(2, 5)
    |
    input.class: input_box

    op: |md
      ReLU<br/>depth: 2
    |
    op.class: op_box

    output: |md
      output<br/>(2, 5)
    |
    output.class: output_box
  }

  node1 -> node2 -> node3: {class: animated_edge}
}

# Inter-group connections
# group1.node3 -> group2.node1: {class: animated_edge}
# group2.node3 -> group3.node1: {class: animated_edge}
