"""Rendering layer for converting Graphviz files to static image formats.

This package provides functionality to render .gv files generated by the storage
layer into various static image formats (SVG, PNG, PDF) using Graphviz.

Example:
    >>> from vode.nn.render import StaticRenderer
    >>> renderer = StaticRenderer()
    >>> renderer.render('model.gv', 'model.svg', format='svg')
    'model.svg'
"""

from .static_renderer import StaticRenderer

__all__ = ["StaticRenderer"]
